// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200615.7

#ifndef WINRT_SDKTemplate_1_H
#define WINRT_SDKTemplate_1_H
#include "winrt/impl/SDKTemplate.0.h"
WINRT_EXPORT namespace winrt::SDKTemplate
{
    struct __declspec(empty_bases) ICustomTextBox :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICustomTextBox>
    {
        ICustomTextBox(std::nullptr_t = nullptr) noexcept {}
        ICustomTextBox(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMainPage :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMainPage>
    {
        IMainPage(std::nullptr_t = nullptr) noexcept {}
        IMainPage(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMainPageStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMainPageStatics>
    {
        IMainPageStatics(std::nullptr_t = nullptr) noexcept {}
        IMainPageStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScenario1_Launch :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScenario1_Launch>
    {
        IScenario1_Launch(std::nullptr_t = nullptr) noexcept {}
        IScenario1_Launch(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScenario2_ShowHideEvents :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScenario2_ShowHideEvents>
    {
        IScenario2_ShowHideEvents(std::nullptr_t = nullptr) noexcept {}
        IScenario2_ShowHideEvents(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScenario3_ShowHideMethods :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScenario3_ShowHideMethods>
    {
        IScenario3_ShowHideMethods(std::nullptr_t = nullptr) noexcept {}
        IScenario3_ShowHideMethods(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScenario4_ShowView :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScenario4_ShowView>
    {
        IScenario4_ShowView(std::nullptr_t = nullptr) noexcept {}
        IScenario4_ShowView(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
