// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200615.7

void* winrt_make_SDKTemplate_CustomTextBox()
{
    return winrt::detach_abi(winrt::make<winrt::SDKTemplate::factory_implementation::CustomTextBox>());
}
WINRT_EXPORT namespace winrt::SDKTemplate
{
    CustomTextBox::CustomTextBox() :
        CustomTextBox(make<SDKTemplate::implementation::CustomTextBox>())
    {
    }
}
