//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::SDKTemplate::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct Scenario3_ShowHideMethodsT : public ::winrt::SDKTemplate::implementation::Scenario3_ShowHideMethods_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename Scenario3_ShowHideMethodsT::base_type;
        using base_type::base_type;
        using class_type = typename Scenario3_ShowHideMethodsT::class_type;

        void InitializeComponent();
        void Connect(int32_t connectionId, IInspectable const& target);
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Media::Animation::Storyboard FadeOutResults()
        {
            return _FadeOutResults;
        }
        void FadeOutResults(::winrt::Windows::UI::Xaml::Media::Animation::Storyboard value)
        {
            _FadeOutResults = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBox WordListBox()
        {
            return _WordListBox;
        }
        void WordListBox(::winrt::Windows::UI::Xaml::Controls::TextBox value)
        {
            _WordListBox = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock ResultsTextBlock()
        {
            return _ResultsTextBlock;
        }
        void ResultsTextBlock(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _ResultsTextBlock = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct Scenario3_ShowHideMethods_obj1_Bindings;

        ::winrt::Windows::UI::Xaml::Media::Animation::Storyboard _FadeOutResults{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBox _WordListBox{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _ResultsTextBlock{nullptr};
    };
}

