//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include "XamlBindingInfo.xaml.g.h"

namespace winrt::SDKTemplate::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainPageT : public ::winrt::SDKTemplate::implementation::MainPage_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename MainPageT::base_type;
        using base_type::base_type;
        using class_type = typename MainPageT::class_type;

        void InitializeComponent();
        void Connect(int32_t connectionId, IInspectable const& target);
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Controls::SplitView Splitter()
        {
            return _Splitter;
        }
        void Splitter(::winrt::Windows::UI::Xaml::Controls::SplitView value)
        {
            _Splitter = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::StackPanel HeaderPanel()
        {
            return _HeaderPanel;
        }
        void HeaderPanel(::winrt::Windows::UI::Xaml::Controls::StackPanel value)
        {
            _HeaderPanel = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Image WindowsLogo()
        {
            return _WindowsLogo;
        }
        void WindowsLogo(::winrt::Windows::UI::Xaml::Controls::Image value)
        {
            _WindowsLogo = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock Header()
        {
            return _Header;
        }
        void Header(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _Header = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::FontIcon Hamburger()
        {
            return _Hamburger;
        }
        void Hamburger(::winrt::Windows::UI::Xaml::Controls::FontIcon value)
        {
            _Hamburger = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock SampleTitle()
        {
            return _SampleTitle;
        }
        void SampleTitle(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _SampleTitle = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::ListBox ScenarioControl()
        {
            return _ScenarioControl;
        }
        void ScenarioControl(::winrt::Windows::UI::Xaml::Controls::ListBox value)
        {
            _ScenarioControl = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::StackPanel FooterPanel()
        {
            return _FooterPanel;
        }
        void FooterPanel(::winrt::Windows::UI::Xaml::Controls::StackPanel value)
        {
            _FooterPanel = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock Copyright()
        {
            return _Copyright;
        }
        void Copyright(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _Copyright = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::StackPanel LinksPanel()
        {
            return _LinksPanel;
        }
        void LinksPanel(::winrt::Windows::UI::Xaml::Controls::StackPanel value)
        {
            _LinksPanel = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::HyperlinkButton PrivacyLink()
        {
            return _PrivacyLink;
        }
        void PrivacyLink(::winrt::Windows::UI::Xaml::Controls::HyperlinkButton value)
        {
            _PrivacyLink = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Frame ScenarioFrame()
        {
            return _ScenarioFrame;
        }
        void ScenarioFrame(::winrt::Windows::UI::Xaml::Controls::Frame value)
        {
            _ScenarioFrame = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::StackPanel StatusPanel()
        {
            return _StatusPanel;
        }
        void StatusPanel(::winrt::Windows::UI::Xaml::Controls::StackPanel value)
        {
            _StatusPanel = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock StatusLabel()
        {
            return _StatusLabel;
        }
        void StatusLabel(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _StatusLabel = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Border StatusBorder()
        {
            return _StatusBorder;
        }
        void StatusBorder(::winrt::Windows::UI::Xaml::Controls::Border value)
        {
            _StatusBorder = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock StatusBlock()
        {
            return _StatusBlock;
        }
        void StatusBlock(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _StatusBlock = value;
        }
        
         ::winrt::com_ptr<::winrt::SDKTemplate::implementation::XamlBindings> Bindings;

    protected:
        bool _contentLoaded{false};

    private:
        struct MainPage_obj16_Bindings;
        struct MainPage_obj1_Bindings;

        ::winrt::Windows::UI::Xaml::Controls::SplitView _Splitter{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::StackPanel _HeaderPanel{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Image _WindowsLogo{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _Header{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::FontIcon _Hamburger{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _SampleTitle{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::ListBox _ScenarioControl{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::StackPanel _FooterPanel{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _Copyright{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::StackPanel _LinksPanel{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::HyperlinkButton _PrivacyLink{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Frame _ScenarioFrame{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::StackPanel _StatusPanel{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _StatusLabel{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Border _StatusBorder{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _StatusBlock{nullptr};
    };
}

