// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200615.7

#include "pch.h"
#include "winrt/base.h"
void* winrt_make_SDKTemplate_CustomTextBox();
void* winrt_make_SDKTemplate_MainPage();
void* winrt_make_SDKTemplate_Scenario1_Launch();
void* winrt_make_SDKTemplate_Scenario2_ShowHideEvents();
void* winrt_make_SDKTemplate_Scenario3_ShowHideMethods();
void* winrt_make_SDKTemplate_Scenario4_ShowView();
void* winrt_make_SDKTemplate_XamlMetaDataProvider();

bool __stdcall winrt_can_unload_now() noexcept
{
    if (winrt::get_module_lock())
    {
        return false;
    }

    winrt::clear_factory_cache();
    return true;
}

void* __stdcall winrt_get_activation_factory([[maybe_unused]] std::wstring_view const& name)
{
    auto requal = [](std::wstring_view const& left, std::wstring_view const& right) noexcept
    {
        return std::equal(left.rbegin(), left.rend(), right.rbegin(), right.rend());
    };

    if (requal(name, L"SDKTemplate.CustomTextBox"))
    {
        return winrt_make_SDKTemplate_CustomTextBox();
    }

    if (requal(name, L"SDKTemplate.MainPage"))
    {
        return winrt_make_SDKTemplate_MainPage();
    }

    if (requal(name, L"SDKTemplate.Scenario1_Launch"))
    {
        return winrt_make_SDKTemplate_Scenario1_Launch();
    }

    if (requal(name, L"SDKTemplate.Scenario2_ShowHideEvents"))
    {
        return winrt_make_SDKTemplate_Scenario2_ShowHideEvents();
    }

    if (requal(name, L"SDKTemplate.Scenario3_ShowHideMethods"))
    {
        return winrt_make_SDKTemplate_Scenario3_ShowHideMethods();
    }

    if (requal(name, L"SDKTemplate.Scenario4_ShowView"))
    {
        return winrt_make_SDKTemplate_Scenario4_ShowView();
    }

    if (requal(name, L"SDKTemplate.XamlMetaDataProvider"))
    {
        return winrt_make_SDKTemplate_XamlMetaDataProvider();
    }

    return nullptr;
}

int32_t __stdcall WINRT_CanUnloadNow() noexcept
{
#ifdef _WRL_MODULE_H_
    if (!::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().Terminate())
    {
        return 1;
    }
#endif

    return winrt_can_unload_now() ? 0 : 1;
}

int32_t __stdcall WINRT_GetActivationFactory(void* classId, void** factory) noexcept try
{
    std::wstring_view const name{ *reinterpret_cast<winrt::hstring*>(&classId) };
    *factory = winrt_get_activation_factory(name);

    if (*factory)
    {
        return 0;
    }

#ifdef _WRL_MODULE_H_
    return ::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().GetActivationFactory(static_cast<HSTRING>(classId), reinterpret_cast<::IActivationFactory**>(factory));
#else
    return winrt::hresult_class_not_available(name).to_abi();
#endif
}
catch (...) { return winrt::to_hresult(); }
