//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::SDKTemplate::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct Scenario2_ShowHideEventsT : public ::winrt::SDKTemplate::implementation::Scenario2_ShowHideEvents_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename Scenario2_ShowHideEventsT::base_type;
        using base_type::base_type;
        using class_type = typename Scenario2_ShowHideEventsT::class_type;

        void InitializeComponent();
        void Connect(int32_t connectionId, IInspectable const& target);
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Documents::Run LastInputPaneEventRun()
        {
            return _LastInputPaneEventRun;
        }
        void LastInputPaneEventRun(::winrt::Windows::UI::Xaml::Documents::Run value)
        {
            _LastInputPaneEventRun = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct Scenario2_ShowHideEvents_obj1_Bindings;

        ::winrt::Windows::UI::Xaml::Documents::Run _LastInputPaneEventRun{nullptr};
    };
}

