// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200615.7

void* winrt_make_SDKTemplate_Scenario2_ShowHideEvents()
{
    return winrt::detach_abi(winrt::make<winrt::SDKTemplate::factory_implementation::Scenario2_ShowHideEvents>());
}
WINRT_EXPORT namespace winrt::SDKTemplate
{
    Scenario2_ShowHideEvents::Scenario2_ShowHideEvents() :
        Scenario2_ShowHideEvents(make<SDKTemplate::implementation::Scenario2_ShowHideEvents>())
    {
    }
}
