// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200615.7

void* winrt_make_SDKTemplate_Scenario1_Launch()
{
    return winrt::detach_abi(winrt::make<winrt::SDKTemplate::factory_implementation::Scenario1_Launch>());
}
WINRT_EXPORT namespace winrt::SDKTemplate
{
    Scenario1_Launch::Scenario1_Launch() :
        Scenario1_Launch(make<SDKTemplate::implementation::Scenario1_Launch>())
    {
    }
}
