// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200615.7

void* winrt_make_SDKTemplate_Scenario3_ShowHideMethods()
{
    return winrt::detach_abi(winrt::make<winrt::SDKTemplate::factory_implementation::Scenario3_ShowHideMethods>());
}
WINRT_EXPORT namespace winrt::SDKTemplate
{
    Scenario3_ShowHideMethods::Scenario3_ShowHideMethods() :
        Scenario3_ShowHideMethods(make<SDKTemplate::implementation::Scenario3_ShowHideMethods>())
    {
    }
}
