// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200615.7

void* winrt_make_SDKTemplate_Scenario4_ShowView()
{
    return winrt::detach_abi(winrt::make<winrt::SDKTemplate::factory_implementation::Scenario4_ShowView>());
}
WINRT_EXPORT namespace winrt::SDKTemplate
{
    Scenario4_ShowView::Scenario4_ShowView() :
        Scenario4_ShowView(make<SDKTemplate::implementation::Scenario4_ShowView>())
    {
    }
}
